"""CLI: proofread a .docx / .xml technical manual.

  python main.py manual.xml --expected-customer "Acme Defense Systems, Inc."
  python main.py manual.docx --no-llm            # deterministic passes only

Writes <name>.findings.json (full structured output) and <name>.report.md.
Set OPENAI_BASE_URL and MODEL (or pass --base-url/--model) for the LLM pass.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

from extract import load, apply_reference_acronyms
import checks
import judge as judge_mod


def gather(doc, expected_customer, min_count):
    phrases = checks.find_recurring_phrases(doc, min_count=min_count)
    apply_reference_acronyms(doc)          # merge in the built-in house acronym reference
    acro_findings, acro_defs = checks.acronym_consistency(doc)
    clusters, cust_findings = checks.customer_consistency(doc, expected=expected_customer)
    org_words = [w for c in clusters.values() for s in c.surfaces
                 for w in checks.WORD_RE.findall(s)]
    extra = ([expected_customer] if expected_customer else []) + org_words
    allow = checks.build_allowlist(doc, phrases, acro_defs, extra=extra)
    spell = checks.spelling_candidates(doc, allow)
    page_findings, toc_entries, total = checks.page_checks(doc)
    return {
        "recurring_phrases": [vars(p) for p in phrases],
        "existing_acronyms": acro_defs,
        "acronym_issues": [vars(f) for f in acro_findings],
        "spelling_candidates": [vars(s) for s in spell],
        "page": {
            "issues": [vars(f) for f in page_findings],
            "toc_entries": toc_entries,
            "total_pages_detected": total,
            "note": ("Page checks cover explicit page markers, 'Page X of Y' footers, and "
                     "cross-reference ranges. Verifying that a TOC/cross-ref target lands on the "
                     "correct rendered page needs a paginated render -- convert docx->PDF with "
                     "headless LibreOffice, or start from a PDF source."),
        },
        "organizations": {
            "clusters": {k: {"surfaces": c.surfaces} for k, c in clusters.items()},
            "issues": cust_findings,
        },
        "_doc_text": doc.text,
    }


def _provenance(model_result):
    """One-line, human-readable statement of where the findings came from."""
    if model_result is None:
        return "_Model pass skipped — findings below are deterministic only._"
    if not isinstance(model_result, dict):
        return "_Model pass: unknown state — deterministic findings shown._"
    meta = model_result.get("_meta") or {}
    tok = (meta.get("usage") or {}).get("completion_tokens")
    who = meta.get("model_reported") or meta.get("model_requested") or "model"
    lat = meta.get("latency_ms")
    if "_error" in model_result:
        return (f"_Model pass FAILED ({model_result['_error']}). "
                f"Findings below are deterministic only._")
    if "_parse_error" in model_result:
        base = ("_Model **responded** but its output was not valid JSON, so deterministic "
                "findings are shown._")
        if tok is not None:
            base = base[:-1] + f" (model `{who}`, {tok} completion tokens, {lat} ms)_"
        return base
    extra = f", {tok} completion tokens" if tok is not None else ""
    extra += f", {lat} ms" if lat is not None else ""
    notes = []
    s = meta.get("findings_shrunk")
    if s:
        notes.append(f"oversized findings were shrunk to fit the prompt budget, "
                     f"{s.get('original_chars', 0):,} -> {s.get('sent_chars', 0):,} chars "
                     f"({'; '.join(s.get('steps') or [])})")
    r = meta.get("retries") or {}
    if r.get("truncation", {}).get("recovered"):
        np = r["truncation"].get("num_predict") or ["?", "?"]
        notes.append(f"recovered from a truncated reply by retrying at num_predict {np[0]} -> {np[-1]}")
    if r.get("repair", {}).get("recovered"):
        notes.append("recovered via one JSON-repair round")
    if r.get("validation", {}).get("recovered"):
        notes.append("recovered via one validation-repair round")
    elif r.get("validation", {}).get("attempted"):
        notes.append("a validation repair was attempted; the original judgment was kept")
    tail = (" _Note: " + "; ".join(notes) + "._") if notes else ""
    return f"_Generated by model `{who}`{extra}._" + tail


def _drop_phantom_acronyms(rows):
    """Drop *proposed* rows with no textual evidence -- the acronym never appears AND its
    expansion never appears in the document (both counts 0). Those are n-gram artifacts
    (e.g. phrases stitched across table cells), not real recurring phrases. Defined/existing
    rows are always kept. Call only after annotate_acronym_counts has set the counts."""
    return [r for r in rows
            if r.get("status") != "proposed"
            or r.get("acronym_count") or r.get("expansion_count")]


def _md_cell(v):
    """One markdown table cell: stringify (so a non-string model value never crashes the
    join) and escape '|' so a pipe in an expansion/note can't break the table."""
    return str("" if v is None else v).replace("|", "\\|")


def _emit_acronym_table(L, rows, title, with_counts):
    """Append one acronym table (title, header, separator, rows, trailing blank) to L.
    The column schema lives ONLY here, so the model branch and the deterministic-fallback
    branch cannot silently drift to different columns."""
    if with_counts:
        cols = ("acronym", "expansion", "status", "acronym_count", "expansion_count", "note")
        header = "| Acronym | Expansion | Status | Acronym uses | Expansion uses | Note |"
        sep = "|---|---|---|---|---|---|"
    else:
        cols = ("acronym", "expansion", "status", "note")
        header = "| Acronym | Expansion | Status | Note |"
        sep = "|---|---|---|---|"
    L += [title, "", header, sep]
    for r in rows:
        L.append("| " + " | ".join(_md_cell(r.get(c, "")) for c in cols) + " |")
    L.append("")


def render_md(f, model_result):
    clean = (isinstance(model_result, dict)
             and "_error" not in model_result and "_parse_error" not in model_result)
    llm = model_result if clean else None

    L = ["# Proofreading report", "", _provenance(model_result), ""]

    if llm and llm.get("acronym_table"):
        meta = (model_result.get("_meta") or {})
        who = meta.get("model_reported") or meta.get("model_requested") or "model"
        rows = sorted(llm["acronym_table"], key=lambda r: (r.get("acronym") or "").upper())
        doctext = f.get("_doc_text") or ""
        if doctext:
            checks.annotate_acronym_counts(rows, doctext)   # exact counts, not the model's
            rows = _drop_phantom_acronyms(rows)
            _emit_acronym_table(
                L, rows,
                f"## Acronym table  _(generated by {who}; uses are exact counts from the document)_",
                with_counts=True)
        else:
            _emit_acronym_table(L, rows, f"## Acronym table  _(generated by {who})_",
                                with_counts=False)
    else:
        # No model table (model skipped, errored, or echoed the input instead of
        # transforming it) -> build the table deterministically so the report is never
        # table-less: glossary/defined acronyms as "existing", recurring long phrases as
        # "proposed". Same count columns as the model branch.
        rows = []
        for acr, exps in sorted((f.get("existing_acronyms") or {}).items()):
            rows.append({"acronym": acr, "expansion": (exps[0] if exps else ""),
                         "status": "existing",
                         "note": ("also: " + "; ".join(exps[1:])) if len(exps) > 1 else ""})
        seen = {r["acronym"] for r in rows}
        for p in f.get("recurring_phrases", []):
            prop = p.get("proposed", "")
            if prop and prop not in seen:
                rows.append({"acronym": prop, "expansion": p.get("phrase", ""),
                             "status": "proposed", "note": ""})
                seen.add(prop)
        # Accurate provenance: distinguish --no-llm, a failed model pass, and a clean
        # model pass that simply produced an empty acronym_table (the old label wrongly
        # said "model echoed input" for that last, correct-but-empty case).
        if model_result is None:
            src = "deterministic"
        elif llm is None:
            src = "deterministic — model pass unavailable"
        else:
            src = "deterministic — model returned an empty table"
        doctext = f.get("_doc_text") or ""
        if doctext and hasattr(checks, "annotate_acronym_counts"):
            checks.annotate_acronym_counts(rows, doctext)
            rows = _drop_phantom_acronyms(rows)
            _emit_acronym_table(
                L, rows, f"## Acronym table  _({src}; uses are exact counts from the document)_",
                with_counts=True)
        else:
            _emit_acronym_table(L, rows, f"## Acronym table  _({src})_", with_counts=False)

    if llm is not None:
        issues = llm.get("acronym_issues") or []      # trust the model's curated list
    else:
        issues = f.get("acronym_issues") or []         # no model pass -> deterministic
    if issues:
        L += ["## Acronym issues", ""]
        for i in sorted(issues, key=lambda i: (i.get("acronym") or "").upper()):
            L.append(f"- `{i.get('acronym','')}` — {i.get('problem','')}: "
                     f"{i.get('detail', i.get('note',''))}")
        L.append("")

    sp = llm.get("misspellings") if llm else None
    if sp is None:
        sp = [{"word": s["word"], "suggestion": s["suggestion"], "context": s["context"]}
              for s in (f.get("spelling_candidates") or [])]
    if sp:
        L += ["## Possible misspellings", ""]
        for s in sp[:60]:
            L.append(f"- **{s.get('word','')}** → {s.get('suggestion','')}  "
                     f"_{s.get('context','')}_")
        L.append("")

    page = f.get("page") or {}
    if page.get("issues"):
        L += ["## Page-number issues", ""]
        for i in page["issues"]:
            L.append(f"- {i['problem']}: {i['detail']} ({i['location']})")
        L.append("")
    if page.get("note"):
        L += [f"> {page['note']}", ""]

    L += ["## Customer name", ""]
    cust = llm.get("customer") if llm else None
    if cust:
        L.append(f"- Primary: **{cust.get('primary','?')}**")
        # Coerce to str + require a list: on the /v1 fallback or PROOFER_SCHEMA=0 path
        # these arrays are unvalidated, and a non-string item would crash str.join and
        # abort the whole report.
        norm = cust.get("normalize")
        if isinstance(norm, list) and any(x for x in norm):
            L.append(f"- Normalize variants: {', '.join(str(x) for x in norm if x)}")
        sw = cust.get("suspected_wrong")
        if isinstance(sw, list) and any(x for x in sw):
            L.append("- ⚠ Suspected wrong/leftover: " + ", ".join(str(x) for x in sw if x))
    else:
        # model gave no customer (skipped, errored, or echoed input) -> deterministic orgs
        orgs = f.get("organizations") or {}
        clusters = {k: c for k, c in (orgs.get("clusters") or {}).items() if c.get("surfaces")}
        if clusters:
            top = max(clusters.values(), key=lambda c: sum(c["surfaces"].values()))
            primary = max(top["surfaces"], key=top["surfaces"].get)
            L.append(f"- Primary (deterministic): **{primary}**")
        for prob, detail in (orgs.get("issues") or []):
            L.append(f"- {prob}: {detail}")

    meta = (model_result.get("_meta") if isinstance(model_result, dict) else None) or {}
    if meta:
        u = meta.get("usage") or {}
        L += ["", "## Analysis provenance", "",
              f"- Model requested: `{meta.get('model_requested','?')}`",
              f"- Model reported by server: `{meta.get('model_reported','?')}`",
              f"- Endpoint: `{meta.get('base_url','?')}`",
              f"- Tokens — prompt {u.get('prompt_tokens','?')}, "
              f"completion {u.get('completion_tokens','?')}, total {u.get('total_tokens','?')}",
              f"- Latency: {meta.get('latency_ms','?')} ms · finish: `{meta.get('finish_reason','?')}`"]
    elif model_result is None:
        L += ["", "## Analysis provenance", "", "- Model pass skipped (`--no-llm`)."]

    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Proofread a .docx/.xml technical manual.")
    ap.add_argument("input")
    ap.add_argument("--expected-customer", default=None)
    ap.add_argument("--min-count", type=int, default=3)
    ap.add_argument("--no-llm", action="store_true", help="skip the model judgment pass")
    ap.add_argument("--model", default=None)
    ap.add_argument("--base-url", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args(argv)

    doc = load(args.input)
    findings = gather(doc, args.expected_customer, args.min_count)

    llm = None
    if not args.no_llm:
        try:
            llm = judge_mod.judge(findings, base_url=args.base_url, model=args.model)
        except Exception as e:
            llm = {"_error": f"model pass failed: {e}"}

    base = Path(args.out) if args.out else Path(args.input).with_suffix("")
    json_path = base.with_name(base.name + ".findings.json")
    md_path = base.with_name(base.name + ".report.md")
    json_path.write_text(json.dumps({"deterministic": findings, "model": llm},
                                     indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(render_md(findings, llm), encoding="utf-8")
    print(f"Wrote {md_path} and {json_path}")
    if llm and ("_error" in llm or "_parse_error" in llm):
        print(f"(model pass unavailable: {llm.get('_error') or llm.get('_parse_error')})")


if __name__ == "__main__":
    main()
