import os, tempfile, threading, time, sys

# --- env must be set BEFORE importing the server module ---
TMP = tempfile.mkdtemp(prefix="proofer_test_")
os.environ["PROOFER_DATA"] = TMP
os.environ["PROOFER_PER_SESSION_CAP"] = "2"
os.environ["PROOFER_MAX_QUEUE"] = "100"
os.environ["PROOFER_MODEL_LANES"] = "1"

import judge as judge_mod

GATE = threading.Event()          # closed -> fake judge blocks (job stays "judging")
def fake_judge(findings, base_url=None, model=None, context=None, timeout=None):
    GATE.wait(timeout=15)
    return {"acronym_table": [{"acronym": "LRU", "expansion": "Line Replaceable Unit",
                               "status": "ok", "note": ""}],
            "acronym_issues": [], "misspellings": [], "customer": {"primary": "Acme"},
            "_meta": {"model_reported": "fake", "model_requested": "fake",
                      "base_url": "mock", "finish_reason": "stop",
                      "usage": {"prompt_tokens": 10, "completion_tokens": 5, "total_tokens": 15},
                      "latency_ms": 1234}}
judge_mod.judge = fake_judge
judge_mod.probe = lambda *a, **k: {"reachable": True, "model_reported": "fake"}

import server as S
from fastapi.testclient import TestClient

FIX = os.path.join(os.path.dirname(S.__file__), "sample_manual.xml")
PASS, FAIL = [], []
def ok(name, cond):
    (PASS if cond else FAIL).append(name)
    print(("PASS " if cond else "FAIL ") + name)

def upload(client, no_llm):
    with open(FIX, "rb") as fh:
        return client.post("/api/jobs",
                           files={"file": ("sample_manual.xml", fh, "application/xml")},
                           data={"no_llm": str(no_llm).lower()})

def wait_status(client, jid, want, timeout=10):
    t = time.time()
    while time.time() - t < timeout:
        r = client.get(f"/api/jobs/{jid}")
        if r.status_code == 200 and r.json().get("status") in want:
            return r.json()
        time.sleep(0.05)
    return client.get(f"/api/jobs/{jid}").json()

c1 = TestClient(S.app)

# 1) no_llm end-to-end + cookie issuance
GATE.set()                                   # not used on no_llm path, but harmless
r = upload(c1, no_llm=True)
ok("1a no_llm submit 200", r.status_code == 200)
ok("1b session cookie issued", S.SESSION_COOKIE in r.cookies or S.SESSION_COOKIE in c1.cookies)
jid1 = r.json()["job_id"]
st = wait_status(c1, jid1, {"done"})
ok("1c no_llm reaches done", st.get("status") == "done")
rep = c1.get(f"/api/jobs/{jid1}/report")
ok("1d report served + deterministic-only", rep.status_code == 200 and "skipped" in rep.text.lower())
fnd = c1.get(f"/api/jobs/{jid1}/findings")
ok("1e findings model is null", fnd.status_code == 200 and fnd.json().get("model") is None)

# 2) session scoping: a different browser cannot see c1's job
c2 = TestClient(S.app)
ok("2a other session 404 on status", c2.get(f"/api/jobs/{jid1}").status_code == 404)
ok("2b other session 404 on report", c2.get(f"/api/jobs/{jid1}/report").status_code == 404)
ok("2c other session empty list", c2.get("/api/jobs").json()["jobs"] == [])

# 3) caller's own list is scoped to them
lst = c1.get("/api/jobs").json()["jobs"]
ok("3a own list has the job", any(j["job_id"] == jid1 for j in lst))

# 4) two-stage states + per-session cap (model ON, gate CLOSED so judging blocks)
GATE.clear()
ra = upload(c1, no_llm=False)
jidA = ra.json()["job_id"]
stA = wait_status(c1, jidA, {"judging"})
ok("4a job A reaches judging (stage B)", stA.get("status") == "judging")
rb = upload(c1, no_llm=False)
jidB = rb.json()["job_id"]
stB = wait_status(c1, jidB, {"awaiting_model"})
ok("4b job B waits in awaiting_model", stB.get("status") == "awaiting_model")
ok("4c awaiting exposes position/eta", "position" in stB)
rc = upload(c1, no_llm=False)                # session now has 2 active -> cap hit
ok("4d third submit hits per-session cap 429", rc.status_code == 429)

# 5) cancel: awaiting -> canceled ; judging -> 409
ok("5a cancel awaiting B -> canceled", c1.delete(f"/api/jobs/{jidB}").json().get("status") == "canceled")
ok("5b cancel judging A -> 409", c1.delete(f"/api/jobs/{jidA}").status_code == 409)

# 6) queue endpoint shape
q = c1.get("/api/queue").json()
ok("6a queue has expected keys",
   all(k in q for k in ("depth", "judging", "lanes", "avg_model_latency_ms", "your_position")))
ok("6b lanes reflects MODEL_LANES", q["lanes"] == 1)

# 7) release the model -> A completes cleanly
GATE.set()
stA2 = wait_status(c1, jidA, {"done"})
ok("7a job A completes after model", stA2.get("status") == "done")
ok("7b model_ok true on clean result", stA2.get("model_ok") is True)
repA = c1.get(f"/api/jobs/{jidA}/report").text
ok("7c report shows model provenance", "generated by model" in repA.lower())

# 8) fairness unit check (direct): least-recently-served session goes first
with S._lock:
    S._jobs.clear(); S._last_served.clear()
    S._jobs["x"] = {"status": "awaiting_model", "session": "A", "enqueued_at": 1.0, "canceled": False}
    S._jobs["y"] = {"status": "awaiting_model", "session": "B", "enqueued_at": 2.0, "canceled": False}
    S._last_served["A"] = 5     # A served recently
    S._last_served["B"] = 1     # B served long ago -> should go first
    order = S._fair_order_locked()
    pick = S._pick_next_locked()
ok("8a fair order puts least-recently-served first", order[0] == "y")
ok("8b pick_next respects fairness", pick == "y")

print(f"\n=== {len(PASS)} passed, {len(FAIL)} failed ===")
if FAIL:
    print("FAILURES:", FAIL); sys.exit(1)
